### ISSUE TITLE
Development of to-do page features

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#14]
Issue to documentation of to-do page test cases: #2 
Dev team to refer to the above issue which contains to-do page test cases documentation and to start developing to-do page features.

**Comment by dianizzati** [comment]
@geraldngkj98 Please assign for testing.

**Comment by geraldngkj98** [comment]
Hi @zxnlee, please work on the testing for the to-do page, thanks.

**Comment by zxnlee** [comment]
@geraldngkj98 @dianizzati Tested and working

**Comment by dianizzati** [comment]
Testing done and merged to master, issue closed.
