### ISSUE TITLE
Selenium/Pytest Test Cases for to-do history page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#15]
Issue to to-do history test case documentation #3 
QA team to work on the selenium/pytest test cases for the to-do history page

**Comment by geraldngkj98** [comment]
@SandyK95 #3 issue has been updated with additional test case. Please update accordingly, thank you.

**Comment by zxnlee** [comment]
Tested by @SandyK95 and working. Issue closed.

_Originally posted by @zxnlee in https://github.com/zxnlee/ETI_ToDoList/issues/24#issuecomment-567547084_
