### ISSUE TITLE
Test case documentation for to-do page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#2]
QA team to work on the test case documentation for the to-do page.
The to-do page contains:
- All To-Do items to be shown to valid User after log in regardless of the owner of the To-Do items.
- Options to delete, add, archive to history buttons.

**Comment by dianizzati** [comment]
Testing done and merged to master, issue closed.

_Originally posted by @dianizzati in https://github.com/zxnlee/ETI_ToDoList/issues/14#issuecomment-561431597_
