### ISSUE TITLE
Development of User Registration page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#21]
Issue to documentation of registration test cases: #18 
Dev team to refer to the above issue for the registration test cases documentation and to start developing registration features.

**Comment by zxnlee** [comment]
@geraldngkj98 I have committed the codes for the user registration feature. Please assign for testing.

**Comment by geraldngkj98** [comment]
@SandyK95 Please work on the testing for the registration page. Thank you.

**Comment by SandyK95** [comment]
@zxnlee @geraldngkj98 Tested and working

**Comment by zxnlee** [comment]
Testing done and merged to master, issue closed.
