### ISSUE TITLE
Selenium/Pytest test cases for registration page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#22]
Issue to registration test case documentation #18 
QA team to work on the selenium/pytest test cases for the registration page

**Comment by geraldngkj98** [comment]
@SandyK95 #18 Test cases has been added, please work on the tests for the registration page. Thanks.

**Comment by zxnlee** [comment]
Testing done and merged to master, issue closed.

_Originally posted by @zxnlee in https://github.com/zxnlee/ETI_ToDoList/issues/21#issuecomment-566619414_
