### ISSUE TITLE
Update Selenium/Pytest test cases for new to-do page features

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#23]
QA team to refer to #19 for the new requirements and update the selenium/pytest test cases accordingly.

**Comment by geraldngkj98** [comment]
@zxnlee Updated test cases for todo page, please work on the tests. Thank you.

**Comment by zxnlee** [comment]
@dianizzati Done with test cases, please assign for development

**Comment by zxnlee** [comment]
Enhancement tested and working, merged to master. Issue closed.

_Originally posted by @zxnlee in https://github.com/zxnlee/ETI_ToDoList/issues/25#issuecomment-567291594_
