### ISSUE TITLE
Development of to-do history page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#24]
Issue to documentation of todo-history test cases: #3 
Dev team to refer to the above issue which contains todo-history test cases documentation and to start developing to-do history page features.

**Comment by kkwwnnpp** [comment]
@geraldngkj98 Development done. Please assign for testing.

**Comment by geraldngkj98** [comment]
@SandyK95 Please do testing on the todo history page. Thank you.

**Comment by kkwwnnpp** [comment]
Testers, take note to run the two commands before testing:
python manage.py makemigrations
python manage.py migrate

**Comment by SandyK95** [comment]
@kkwwnnpp @zxnlee @geraldngkj98 @dianizzati Tested and working.

**Comment by kkwwnnpp** [comment]
@zxnlee Merged to master.

**Comment by zxnlee** [comment]
Tested by @SandyK95 and working. Issue closed.
