### ISSUE TITLE
Enhancement for the to-do page

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#25]
The to-do page has new enhancements to be made. Refer to test case #19  for the new requirements and develop the todo page.

**Comment by zxnlee** [comment]
#23 @dianizzati Done with test cases for to-do page. Please assign and proceed with development.

**Comment by dianizzati** [comment]
@geraldngkj98 Development done. Please assign for testing

**Comment by dianizzati** [comment]
Tester, note that you need to run:
python manage.py makemigrations
python manage.py migrate
before you start testing.

**Comment by geraldngkj98** [comment]
@zxnlee Please do testing for issue #23. Thank you.

**Comment by zxnlee** [comment]
@geraldngkj98 @dianizzati Tested and working

**Comment by dianizzati** [comment]
@zxnlee Merged to master

**Comment by zxnlee** [comment]
Enhancement tested and working, merged to master. Issue closed.
