### ISSUE TITLE
Integration test for sprint 1 + 2

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#34]
Test cases merged to master to go through integration testing and codes or test cases to be updated depending on outcome.

**Comment by zxnlee** [comment]
test_cases_login.py:
![image](https://user-images.githubusercontent.com/56616436/71196950-7bdce100-22cb-11ea-8488-ae94555ec2b9.png)
![image](https://user-images.githubusercontent.com/56616436/71196971-8dbe8400-22cb-11ea-9e2f-9d84c8b3b20e.png)
![image](https://user-images.githubusercontent.com/56616436/71196993-99aa4600-22cb-11ea-9aef-eaba1bb0fc01.png)

1. test_successful_login() failed.
2. test_logout() failed.
3. ETIToDoList\todo\models.py missed 1 line.

**Comment by zxnlee** [comment]
test_cases_todo.py:
![image](https://user-images.githubusercontent.com/56616436/71197304-4a184a00-22cc-11ea-8dbc-e29f53db707a.png)
All test cases passed.

**Comment by zxnlee** [comment]
test_cases_todohistory.py:
![image](https://user-images.githubusercontent.com/56616436/71197530-c6ab2880-22cc-11ea-8548-2bf02f4b4186.png)
![image](https://user-images.githubusercontent.com/56616436/71197557-d62a7180-22cc-11ea-9336-5b4dabc1e991.png)

1. test_successful_archive_into_todo_history_page() failed.

**Comment by zxnlee** [comment]
test_cases_registration.py:
![image](https://user-images.githubusercontent.com/56616436/71198571-096e0000-22cf-11ea-840f-3e5cec99ace2.png)

All test cases passed.

**Comment by zxnlee** [comment]
@geraldngkj98 @dianizzati Please note the above passed and failed test cases and fix codes/test cases.

**Comment by geraldngkj98** [comment]
> test_cases_login.py:
> ![image](https://user-images.githubusercontent.com/56616436/71196950-7bdce100-22cb-11ea-8488-ae94555ec2b9.png)
> ![image](https://user-images.githubusercontent.com/56616436/71196971-8dbe8400-22cb-11ea-9e2f-9d84c8b3b20e.png)
> ![image](https://user-images.githubusercontent.com/56616436/71196993-99aa4600-22cb-11ea-9aef-eaba1bb0fc01.png)
> 
> 1. test_successful_login() failed.
> 2. test_logout() failed.
> 3. ETIToDoList\todo\models.py missed 1 line.

test_successful_login() failed because the assert was for a placeholder previously. That page now holds the todo list. Will update test cases.

test_logout() failed because the element was found using the 'a' tag in the test case but there are now multiple 'a' elements. Will update test cases.

**Comment by geraldngkj98** [comment]
> test_cases_todohistory.py:
> ![image](https://user-images.githubusercontent.com/56616436/71197530-c6ab2880-22cc-11ea-8548-2bf02f4b4186.png)
> ![image](https://user-images.githubusercontent.com/56616436/71197557-d62a7180-22cc-11ea-9336-5b4dabc1e991.png)
> 
> 1. test_successful_archive_into_todo_history_page() failed.

test_successful_archive_into_todo_history_page() failed because item added was actually named "Item to be completed" but the assert was "Item to be archived". Will update test cases.

**Comment by geraldngkj98** [comment]
9bd95af Fixed test_cases_login.py.
![image](https://user-images.githubusercontent.com/56948234/71234873-571d5380-2335-11ea-90fd-d914aa7bfc58.png)
![image](https://user-images.githubusercontent.com/56948234/71234885-66040600-2335-11ea-8324-d3e5edd04d6f.png)

**Comment by geraldngkj98** [comment]
7e04f77 Fixed test_cases_todohistory.py.
![image](https://user-images.githubusercontent.com/56948234/71235006-d0b54180-2335-11ea-919f-d7936a1b5106.png)

**Comment by dianizzati** [comment]
> > test_cases_login.py:
> > ![image](https://user-images.githubusercontent.com/56616436/71196950-7bdce100-22cb-11ea-8488-ae94555ec2b9.png)
> > ![image](https://user-images.githubusercontent.com/56616436/71196971-8dbe8400-22cb-11ea-9e2f-9d84c8b3b20e.png)
> > ![image](https://user-images.githubusercontent.com/56616436/71196993-99aa4600-22cb-11ea-9aef-eaba1bb0fc01.png)
> > 
> > 1. test_successful_login() failed.
> > 2. test_logout() failed.
> > 3. ETIToDoList\todo\models.py missed 1 line.
> 
> test_successful_login() failed because the assert was for a placeholder previously. That page now holds the todo list. Will update test cases.
> 
> test_logout() failed because the element was found using the 'a' tag in the test case but there are now multiple 'a' elements. Will update test cases.

389940c Removed the unnecessary lines from models.py.
@zxnlee Please test again to see if there are still missed lines.

**Comment by zxnlee** [comment]
@dianizzati Yes, its working.
24e1495 Updated test_cases_output_login.png
![image](https://user-images.githubusercontent.com/56616436/71236166-3951ed80-2339-11ea-9598-93ee4bce71b7.png)

**Comment by geraldngkj98** [comment]
@zxnlee #37 has been merged to master, please do integration testing again.

**Comment by zxnlee** [comment]
Integration test completed. All test cases pass.
![test_cases_output_all](https://user-images.githubusercontent.com/56616436/71309469-eb291100-2442-11ea-9960-c8a15946fc6c.png)

**Comment by zxnlee** [comment]
All issues for sprint 1 and 2 done. Issue will be closed.
