### ISSUE TITLE
Enhancement of todo history page - filter todo history by user

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#37]
Development team to work on enhancement of the todo history page to include the new requirement. Refer to #35.

**Comment by geraldngkj98** [comment]
@kkwwnnpp Note that test cases have been added to #35 and #36.

**Comment by kkwwnnpp** [comment]
@geraldngkj98 Please assign for testing.

**Comment by geraldngkj98** [comment]
@kkwwnnpp @zxnlee @dianizzati tested and working

**Comment by zxnlee** [comment]
Testing done and merged to master, issue closed.
