### ISSUE TITLE
Development of login features

### ISSUE THREAD

**Issue by zxnlee** [zxnlee/ETI_ToDoList#6]
Issue to documentation of login test cases: #1 
Dev team to refer to the above issue which contains login test cases documentation and to start developing login features.

**Comment by zxnlee** [comment]
@geraldngkj98
Development for login test cases done, please assign for testing.

**Comment by geraldngkj98** [comment]
@SandyK95 Please do testing on the login feature, thanks.

**Comment by SandyK95** [comment]
@zxnlee @geraldngkj98 Tested and working.

**Comment by zxnlee** [comment]
Added pytest test cases for login. #6 development to be done

_Originally posted by @zxnlee in https://github.com/zxnlee/ETI_ToDoList/issues/7#issuecomment-560134843_

**Comment by zxnlee** [comment]
@SandyK95 Please do testing again

**Comment by SandyK95** [comment]
@zxnlee 
![Screenshot (2)](https://user-images.githubusercontent.com/32905878/69940644-ba2d7e80-151d-11ea-89f7-0066c8753083.png)

Received the following error when running the pytest test cases

**Comment by zxnlee** [comment]
Testing done and merged to master, issue closed.
