### ISSUE TITLE
Selenium/Pytest Test Cases for login page

### ISSUE THREAD

**Issue by geraldngkj98** [zxnlee/ETI_ToDoList#7]
Issue to login test case documentation #1 
QA team to work on the selenium/pytest test cases for the login page

**Comment by geraldngkj98** [comment]
Test cases mainly focusing on input validations.

**Comment by geraldngkj98** [comment]
@SandyK95 @zxnlee Note that 2 test cases have been added to #1

**Comment by SandyK95** [comment]
@zxnlee Note for issue #6: Selenium test cases for login done and committed.

**Comment by zxnlee** [comment]
Added pytest test cases for login. #6 development to be done

**Comment by zxnlee** [comment]
Testing done and merged to master, issue closed.

_Originally posted by @zxnlee in https://github.com/zxnlee/ETI_ToDoList/issues/6#issuecomment-560323771_
