### ISSUE TITLE
Selenium/Pytest Test Cases for ToDoList page

### ISSUE THREAD

**Issue by geraldngkj98** [zxnlee/ETI_ToDoList#8]
Issue to todolist test case documentation #2 
QA team to work on the selenium/pytest test cases for the to-do list page

**Comment by geraldngkj98** [comment]
@zxnlee Can you work on the delete and archive test cases? Thanks.

**Comment by dianizzati** [comment]
Testing done and merged to master, issue closed.

_Originally posted by @dianizzati in https://github.com/zxnlee/ETI_ToDoList/issues/14#issuecomment-561431597_
